apiVersion: v1
kind: Service
metadata:
  name: devops-final-service
  namespace: staging
  labels:
    environment: staging
spec:
  type: ClusterIP  # Staging uses ClusterIP (internal only), no LoadBalancer needed
  selector:
    app: nodejs-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
